my:
  props1:
    prop1: p1p1
    prop2: p1p2
  props2:
    prop1: p2p1
    prop2: p2p2
  props3:
    prop1: p3p1
    prop2: p3p2
  props4:
    prop1: p4p1
    prop2: p4p2
    utils-record:
      nested-prop1: foo
    records-list:
      - nested-prop1: bar
      - nested-prop1: buzz
  props5:
    prop1: p5p1
    prop2: p5p2
  props6:
    prop1: p6p1
    prop2: p6p2
  props0:
    bar-str: p0p1
    foo-str: p0p2
  props7:
    prop1: p7p1
  props8:
    prop1: p8p1
  props9:
    prop1: p9p1
  props00:
    prop1: p00.p1
    prop2: p00.p2
  props10:
    pr2:
      - pr4:
          - pr6: foo

  props12:
    property2:
      nested-prop: sss
      inherited-prop: ttt


